imports:
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/*.yml" }

services:
  _defaults:
    autowire: true
    public: false

  Ivoz\Core\Infrastructure\Domain\Service\Lifecycle\CommandPersister:
    arguments:
      $logger: '@monolog.logger.changelog'

  Ivoz\Core\Infrastructure\Domain\Service\Lifecycle\DoctrineEventSubscriber:
    arguments:
      $serviceContainer: '@service_container'
      $forcedEntityChangeLog: '@=service("kernel").getEnvironment() == "test"'
    tags:
      - { name: doctrine.event_subscriber }

  Ivoz\Core\Domain\Service\CommonLifecycleServiceCollection:
    public: true
  lifecycle.common.service_collection: '@Ivoz\Core\Domain\Service\CommonLifecycleServiceCollection'

  Ivoz\Core\Infrastructure\Persistence\Doctrine\Service\DuplicateEntryCommonErrorHandler:
    tags: [{ name: 'domain.service'}]

  Ivoz\Core\Infrastructure\Persistence\Filesystem\Commit:
    tags: [{ name: 'domain.service'}]

  Ivoz\Core\Infrastructure\Persistence\Filesystem\ScheduleForRemove:
    arguments:
      $serviceContainer: '@service_container'
    tags: [{ name: 'domain.service'}]

  Ivoz\Core\Infrastructure\Persistence\Filesystem\Remove:
    tags: [{ name: 'domain.service'}]
